'use client'

import { useEffect, useMemo, useState } from 'react'

const markets = [
  { key: 'local', label: 'Local Market', score: 92, status: 'Ready', reason: 'Your village and nearby markets already know this craft.', gap: 'Wider product range' },
  { key: 'online', label: 'Online Marketplace', score: 78, status: 'Ready', reason: 'Strong quality and pricing make this a good next step.', gap: 'Digital catalog' },
  { key: 'retail', label: 'Retail / Boutique', score: 65, status: 'Almost ready', reason: 'Boutiques value your finish, but need consistent supply.', gap: 'Packaging' },
  { key: 'wholesale', label: 'Wholesale', score: 54, status: 'Needs work', reason: 'Bulk buyers need higher monthly capacity.', gap: 'Capacity and pricing' },
  { key: 'export', label: 'Export', score: 32, status: 'Not yet', reason: 'Export needs stronger packaging and documentation.', gap: 'Export packaging' },
]

const products = [
  { name: 'Bamboo Basket', price: '₹850', type: 'Bamboo handicraft', category: 'bamboo', rating: 4.6, image: '/bamboo-basket.png' },
  { name: 'Terracotta Diya Set', price: '₹450', type: 'Terracotta', category: 'diya', rating: 4.4, image: '/terracotta-diyas.png' },
  { name: 'Handwoven Saree', price: '₹2,800', type: 'Handloom textile', category: 'textile', rating: 4.2, image: '/handwoven-saree.png' },
  { name: 'Wooden Craft', price: '₹1,200', type: 'Wood craft', category: 'wood', rating: 4.0, image: '/wooden-craft.png' },
]

const copy: Record<string, Record<string, string>> = {
  en: { hello: 'Namaste, Ramesh ji!', intro: 'Let us help your craft reach the right market.', add: 'Add product', markets: 'Find markets', ready: 'My readiness', progress: 'My progress', suggestion: 'AI suggestion', suggestionText: 'Online marketplaces may be a great next step for your Bamboo Basket. Complete your digital catalog before approaching larger buyers.', home: 'Home', products: 'My products', help: 'Help', profile: 'Profile', intelligence: 'Market intelligence', journey: 'Your journey', voice: 'Speak with voice', choose: 'Choose your language', chooseSub: 'Pick the language you feel comfortable using.', continue: 'Continue', select: 'Select language', shop: 'Shop crafts' },
  hi: { hello: 'नमस्ते, रमेश जी!', intro: 'आपके सामान को सही बाज़ार तक पहुँचाने में हम आपकी मदद करेंगे।', add: 'सामान जोड़ें', markets: 'बाज़ार खोजें', ready: 'मेरी तैयारी', progress: 'मेरी प्रगति', suggestion: 'AI सुझाव', suggestionText: 'आपके Bamboo Basket के लिए Online Marketplace अच्छा अगला कदम हो सकता है। बड़े खरीदारों से पहले अपना डिजिटल कैटलॉग पूरा करें।', home: 'होम', products: 'मेरे सामान', help: 'मदद', profile: 'प्रोफ़ाइल', intelligence: 'बाज़ार तैयारी', journey: 'आपकी यात्रा', voice: 'बोलकर बताएं', choose: 'अपनी भाषा चुनें', chooseSub: 'जिस भाषा में सहज हों, उसे चुनें।', continue: 'आगे बढ़ें', select: 'भाषा चुनें', shop: 'सामान खरीदें' },
  te: { hello: 'నమస్కారం, రమేష్ గారు!', intro: 'మీ కళను సరైన మార్కెట్‌కు చేర్చడంలో మేము సహాయం చేస్తాము.', add: 'ఉత్పత్తి చేర్చండి', markets: 'మార్కెట్లు కనుగొనండి', ready: 'నా సిద్ధత', progress: 'నా పురోగతి', suggestion: 'AI సూచన', suggestionText: 'మీ Bamboo Basket కోసం Online Marketplace మంచి తదుపరి అడుగు కావచ్చు. పెద్ద కొనుగోలుదారులను సంప్రదించే ముందు మీ డిజిటల్ కాటలాగ్ పూర్తి చేయండి.', home: 'హోమ్', products: 'నా ఉత్పత్తులు', help: 'సహాయం', profile: 'ప్రొఫైల్', intelligence: 'మార్కెట్ సిద్ధత', journey: 'మీ ప్రయాణం' },
  ta: { hello: 'வணக்கம், ரமேஷ் ji!', intro: 'உங்கள் கைவினைப் பொருளை சரியான சந்தைக்கு கொண்டுசெல்ல நாங்கள் உதவுவோம்.', add: 'பொருள் சேர்', markets: 'சந்தை கண்டுபிடி', ready: 'என் தயார் நிலை', progress: 'என் முன்னேற்றம்', suggestion: 'AI பரிந்துரை', suggestionText: 'உங்கள் Bamboo Basket க்கு Online Marketplace நல்ல அடுத்த படியாக இருக்கலாம். பெரிய வாங்குபவர்களை அணுகும் முன் உங்கள் டிஜிட்டல் பட்டியலை முடிக்கவும்.', home: 'முகப்பு', products: 'என் பொருட்கள்', help: 'உதவி', profile: 'சுயவிவரம்', intelligence: 'சந்தை தயார்', journey: 'உங்கள் பயணம்' },
  ml: { hello: 'നമസ്കാരം, രമേഷ് ji!', intro: 'നിങ്ങളുടെ കരകൗശലം ശരിയായ വിപണിയിൽ എത്തിക്കാൻ ഞങ്ങൾ സഹായിക്കും.', add: 'ഉൽപ്പന്നം ചേർക്കുക', markets: 'മാർക്കറ്റ് കണ്ടെത്തുക', ready: 'എന്റെ തയ്യാറെടുപ്പ്', progress: 'എന്റെ പുരോഗതി', suggestion: 'AI നിർദ്ദേശം', suggestionText: 'നിങ്ങളുടെ Bamboo Basket ന് Online Marketplace നല്ല അടുത്ത പടി ആയേക്കാം. വലിയ വാങ്ങുന്നവരെ സമീപിക്കുന്നതിന് മുമ്പ് ഡിജിറ്റൽ കാറ്റലോഗ് പൂർത്തിയാക്കുക.', home: 'ഹോം', products: 'എന്റെ ഉൽപ്പന്നങ്ങൾ', help: 'സഹായം', profile: 'പ്രൊഫൈൽ', intelligence: 'മാർക്കറ്റ് തയ്യാറെടുപ്പ്', journey: 'നിങ്ങളുടെ യാത്ര' },
  kn: { hello: 'ನಮಸ್ಕಾರ, ರಮೇಶ್ ji!', intro: 'ನಿಮ್ಮ ಕರಕುಶಲವನ್ನು ಸರಿಯಾದ ಮಾರುಕಟ್ಟೆಗೆ ತಲುಪಿಸಲು ನಾವು ಸಹಾಯ ಮಾಡುತ್ತೇವೆ.', add: 'ಉತ್ಪನ್ನ ಸೇರಿಸಿ', markets: 'ಮಾರುಕಟ್ಟೆ ಹುಡುಕಿ', ready: 'ನನ್ನ ಸಿದ್ಧತೆ', progress: 'ನನ್ನ ಪ್ರಗತಿ', suggestion: 'AI ಸಲಹೆ', suggestionText: 'ನಿಮ್ಮ Bamboo Basket ಗೆ Online Marketplace ಉತ್ತಮ ಮುಂದಿನ ಹಂತವಾಗಬಹುದು. ದೊಡ್ಡ ಖರೀದಿದಾರರನ್ನು ಸಂಪರ್ಕಿಸುವ ಮೊದಲು ನಿಮ್ಮ ಡಿಜಿಟಲ್ ಕ್ಯಾಟಲಾಗ್ ಪೂರ್ಣಗೊಳಿಸಿ.', home: 'ಮುಖಪುಟ', products: 'ನನ್ನ ಉತ್ಪನ್ನಗಳು', help: 'ಸಹಾಯ', profile: 'ಪ್ರೊಫೈಲ್', intelligence: 'ಮಾರುಕಟ್ಟೆ ಸಿದ್ಧತೆ', journey: 'ನಿಮ್ಮ ಪ್ರಯಾಣ' },
  bn: { hello: 'নমস্কার, রমেশ ji!', intro: 'আপনার কারুশিল্পকে সঠিক বাজারে পৌঁছাতে আমরা সাহায্য করব।', add: 'পণ্য যোগ করুন', markets: 'বাজার খুঁজুন', ready: 'আমার প্রস্তুতি', progress: 'আমার অগ্রগতি', suggestion: 'AI পরামর্শ', suggestionText: 'আপনার Bamboo Basket এর জন্য Online Marketplace ভালো পরবর্তী পদক্ষেপ হতে পারে। বড় ক্রেতাদের সাথে যোগাযোগের আগে আপনার ডিজিটাল ক্যাটালগ সম্পূর্ণ করুন।', home: 'হোম', products: 'আমার পণ্য', help: 'সহায়তা', profile: 'প্রোফাইল', intelligence: 'বাজার প্রস্তুতি', journey: 'আপনার যাত্রা' },
}

const voiceLabels: Record<string, string> = { en: 'Speak with voice', hi: 'बोलकर बताएं', te: 'వాయిస్‌తో చెప్పండి', ta: 'குரலில் சொல்லுங்கள்', ml: 'വോയിസിൽ പറയുക', kn: 'ಧ್ವನಿಯಲ್ಲಿ ಹೇಳಿ', bn: 'কথা বলে বলুন' }
const shopLabels: Record<string, string> = { en: 'Shop crafts', hi: 'सामान खरीदें', te: 'కళాకృతులు కొనండి', ta: 'கைவினைப் பொருட்கள் வாங்குங்கள்', ml: 'കരകൗശല വസ്തുക്കൾ വാങ്ങുക', kn: 'ಕರಕುಶಲ ವಸ್ತುಗಳನ್ನು ಖರೀದಿಸಿ', bn: 'কারুশিল্প কিনুন' }

const labels: Record<string, { buyers: string; seeAll: string; heroTag: string; heroText: string; heroButton: string; productsEyebrow: string; productsReady: string; why: string; updated: string; buyerMatch: string; gapsTitle: string }> = {
  en: { buyers: 'Buyers', seeAll: 'See all', heroTag: 'AI MARKET INTELLIGENCE', heroText: 'We look at your craft, capacity, location and digital readiness — then explain what to do next.', heroButton: 'View AI recommendation', productsEyebrow: 'PRODUCT CATALOG', productsReady: 'Market-ready products', why: 'Why this fit?', updated: 'Updated today', buyerMatch: 'Buyer matches', gapsTitle: 'Readiness gaps' },
  hi: { buyers: 'खरीदार', seeAll: 'सभी देखें', heroTag: 'AI बाज़ार जानकारी', heroText: 'हम आपकी कला, क्षमता, स्थान और डिजिटल तैयारी देखकर अगला सही कदम बताते हैं।', heroButton: 'AI सुझाव देखें', productsEyebrow: 'उत्पाद सूची', productsReady: 'बाज़ार-तैयार सामान', why: 'यह क्यों सही है?', updated: 'आज अपडेट किया गया', buyerMatch: 'उपयुक्त खरीदार', gapsTitle: 'तैयारी की कमी' },
  te: { buyers: 'కొనుగోలుదారులు', seeAll: 'అన్నీ చూడండి', heroTag: 'AI మార్కెట్ సమాచారం', heroText: 'మీ కళ, సామర్థ్యం, స్థానం, డిజిటల్ సిద్ధతను చూసి తదుపరి సరైన అడుగు సూచిస్తాం.', heroButton: 'AI సూచన చూడండి', productsEyebrow: 'ఉత్పత్తుల జాబితా', productsReady: 'మార్కెట్‌కు సిద్ధమైన ఉత్పత్తులు', why: 'ఇది ఎందుకు సరిపోతుంది?', updated: 'ఈ రోజు నవీకరించబడింది', buyerMatch: 'కొనుగోలుదారుల సరిపోలికలు', gapsTitle: 'సిద్ధతలో లోపాలు' },
  ta: { buyers: 'வாங்குபவர்கள்', seeAll: 'அனைத்தையும் காண்க', heroTag: 'AI சந்தை தகவல்', heroText: 'உங்கள் கைவினை, திறன், இடம், டிஜிட்டல் தயார்நிலையை வைத்து அடுத்த படி சொல்கிறோம்.', heroButton: 'AI பரிந்துரை காண்க', productsEyebrow: 'தயாரிப்பு பட்டியல்', productsReady: 'சந்தைக்கு தயாரான பொருட்கள்', why: 'ஏன் இது பொருந்தும்?', updated: 'இன்று புதுப்பிக்கப்பட்டது', buyerMatch: 'வாங்குபவர் பொருத்தங்கள்', gapsTitle: 'தயார்நிலை இடைவெளிகள்' },
  ml: { buyers: 'വാങ്ങുന്നവർ', seeAll: 'എല്ലാം കാണുക', heroTag: 'AI വിപണി വിവരം', heroText: 'നിങ്ങളുടെ കരകൗശലം, ശേഷി, സ്ഥലം, ഡിജിറ്റൽ തയ്യാറെടുപ്പ് പരിശോധിച്ച് അടുത്ത ഘട്ടം പറയുന്നു.', heroButton: 'AI നിർദ്ദേശം കാണുക', productsEyebrow: 'ഉൽപ്പന്ന പട്ടിക', productsReady: 'വിപണിക്ക് തയ്യാറായ ഉൽപ്പന്നങ്ങൾ', why: 'ഇത് എന്തുകൊണ്ട് അനുയോജ്യം?', updated: 'ഇന്ന് അപ്ഡേറ്റ് ചെയ്തു', buyerMatch: 'വാങ്ങുന്നവരുടെ പൊരുത്തങ്ങൾ', gapsTitle: 'തയ്യാറെടുപ്പ് കുറവുകൾ' },
  kn: { buyers: 'ಖರೀದಿದಾರರು', seeAll: 'ಎಲ್ಲವನ್ನೂ ನೋಡಿ', heroTag: 'AI ಮಾರುಕಟ್ಟೆ ಮಾಹಿತಿ', heroText: 'ನಿಮ್ಮ ಕರಕುಶಲ, ಸಾಮರ್ಥ್ಯ, ಸ್ಥಳ, ಡಿಜಿಟಲ್ ಸಿದ್ಧತೆಯನ್ನು ನೋಡಿ ಮುಂದಿನ ಹಂತ ಸೂಚಿಸುತ್ತೇವೆ.', heroButton: 'AI ಸಲಹೆ ನೋಡಿ', productsEyebrow: 'ಉತ್ಪನ್ನ ಪಟ್ಟಿ', productsReady: 'ಮಾರುಕಟ್ಟೆಗೆ ಸಿದ್ಧ ಉತ್ಪನ್ನಗಳು', why: 'ಇದು ಏಕೆ ಸರಿಹೊಂದುತ್ತದೆ?', updated: 'ಇಂದು ನವೀಕರಿಸಲಾಗಿದೆ', buyerMatch: 'ಖರೀದಿದಾರರ ಹೊಂದಾಣಿಕೆ', gapsTitle: 'ಸಿದ್ಧತೆಯ ಕೊರತೆಗಳು' },
  bn: { buyers: 'ক্রেতা', seeAll: 'সব দেখুন', heroTag: 'AI বাজার তথ্য', heroText: 'আপনার কারুশিল্প, সক্ষমতা, অবস্থান ও ডিজিটাল প্রস্তুতি দেখে পরবর্তী পদক্ষেপ বলি।', heroButton: 'AI পরামর্শ দেখুন', productsEyebrow: 'পণ্যের তালিকা', productsReady: 'বাজার-প্রস্তুত পণ্য', why: 'কেন এটি উপযুক্ত?', updated: 'আজ আপডেট হয়েছে', buyerMatch: 'ক্রেতা মিল', gapsTitle: 'প্রস্তুতির ঘাটতি' },
}

function ProgressBar({ value, tone = 'terracotta' }: { value: number; tone?: 'terracotta' | 'green' | 'mustard' }) {
  return <div className="progress-track" aria-label={`${value}%`}><span className={`progress-fill ${tone}`} style={{ width: `${value}%` }} /></div>
}

function VoiceButton({ onSpeak, label = 'बोलकर बताएं' }: { onSpeak: () => void; label?: string }) {
  const [listening, setListening] = useState(false)
  return <button className={`voice-btn ${listening ? 'listening' : ''}`} onClick={() => { setListening(true); onSpeak(); setTimeout(() => setListening(false), 2200) }} aria-label={label}><span className="mic">🎤</span>{label}</button>
}

export default function Page() {
  const [language, setLanguage] = useState<string | null>(null)
  const [page, setPage] = useState('home')
  const [showLanguage, setShowLanguage] = useState(true)
  const [shopPrice, setShopPrice] = useState(3000)
  const [shopRating, setShopRating] = useState(0)
  const [shopCategory, setShopCategory] = useState('all')

  useEffect(() => {
    const saved = window.localStorage.getItem('craftbridge-language')
    if (saved && copy[saved]) { setLanguage(saved); setShowLanguage(false) }
  }, [])

  const chooseLanguage = (next: string) => {
    setLanguage(next)
    window.localStorage.setItem('craftbridge-language', next)
  }
  const [showAnalysis, setShowAnalysis] = useState(false)
  const [analysisStep, setAnalysisStep] = useState(0)
  const [showBuyer, setShowBuyer] = useState(false)
  const [showProfile, setShowProfile] = useState(false)
  const [toast, setToast] = useState('')
  const [roadmap, setRoadmap] = useState([false, false, true, false])
  const t = copy[language ?? 'hi']
  const l = labels[language ?? 'hi']

  const notify = (message: string) => { setToast(message); setTimeout(() => setToast(''), 2600) }
  const startAnalysis = () => { setShowAnalysis(true); setAnalysisStep(0); const timer = setInterval(() => setAnalysisStep((current) => { if (current >= 5) { clearInterval(timer); return 5 } return current + 1 }), 700); }
  const score = useMemo(() => markets.find((item) => item.key === 'online')!, [])

  if (showLanguage) { const languageCopy = copy[language ?? 'en']; return <main className={`language-page lang-${language ?? 'en'}`}><div className="language-art">🌾</div><div className="language-card"><div className="brand-mark">craft<span>bridge</span><small>AI</small></div><h1>{languageCopy.choose}</h1><p>{languageCopy.chooseSub}</p><div className="lang-grid">{[['hi','हिंदी'],['en','English'],['te','తెలుగు'],['ta','தமிழ்'],['ml','മലയാളം'],['kn','ಕನ್ನಡ'],['bn','বাংলা']].map(([code, label]) => <button key={code} className={`${language === code ? 'active' : ''} lang-${code}`} onClick={() => chooseLanguage(code)}>{label}</button>)}</div><button className="primary-btn" onClick={() => { if (language) setShowLanguage(false) }}>{language ? languageCopy.continue : languageCopy.select}</button></div></main> }

  return <div className={`app-shell lang-${language ?? 'hi'}`}>
    <header className="topbar"><button className="brand" onClick={() => setPage('home')}><span className="brand-symbol">✦</span><span>craft<span>bridge</span><small>AI</small></span></button><div className="top-actions"><button className="pill-btn" onClick={() => setShowProfile(true)}>{t.profile}</button></div></header>
    <main className="content">
      {page === 'home' && <Home t={t} l={l} language={language} onNavigate={setPage} onAnalysis={startAnalysis} onVoice={() => notify('मैं अपने सामान को ऑनलाइन बेचने के लिए क्या करूं?')} />}
      {page === 'products' && <Products t={t} onAdd={startAnalysis} onNavigate={setPage} />}
      {page === 'shop' && <Shop price={shopPrice} setPrice={setShopPrice} rating={shopRating} setRating={setShopRating} category={shopCategory} setCategory={setShopCategory} onContact={() => setShowBuyer(true)} />}
      {page === 'intelligence' && <Intelligence score={score} onNavigate={setPage} roadmap={roadmap} setRoadmap={setRoadmap} />}
      {page === 'buyers' && <Buyers onContact={() => setShowBuyer(true)} />}
      {page === 'progress' && <ProgressView t={t} />}
      {page === 'help' && <Help onVoice={() => notify('AI: Online Marketplace आपके लिए अच्छा विकल्प हो सकता है।')} />}
    </main>
    <nav className="bottom-nav">{[['home','⌂',t.home], ['products','▣',t.products], ['intelligence','◎',t.intelligence], ['shop','⌕',shopLabels[language] || shopLabels.en], ['progress','↗',t.progress]].map(([key, icon, label]) => <button key={key} className={page === key ? 'active' : ''} onClick={() => setPage(key as string)}><span>{icon}</span><small>{label}</small></button>)}</nav>
    {showAnalysis && <AnalysisModal step={analysisStep} onClose={() => { setShowAnalysis(false); setPage('intelligence') }} />}
    {showBuyer && <BuyerModal onClose={() => setShowBuyer(false)} onDone={() => { setShowBuyer(false); notify('Message sent to Dastkar Emporium') }} />}
    {showProfile && <ProfileModal onClose={() => setShowProfile(false)} onSave={() => { setShowProfile(false); notify('Profile updated') }} />}
    {toast && <div className="toast">✓ {toast}</div>}
  </div>
}

function Home({ t, l, language, onNavigate, onAnalysis, onVoice }: any) { return <div className="page-stack"><section className="welcome"><div><p className="eyebrow">CRAFTBRIDGE AI · {t.journey}</p><h1>{t.hello}</h1><p>{t.intro}</p></div><VoiceButton onSpeak={onVoice} label={voiceLabels[language] || voiceLabels.en} /></section><section className="action-grid"><Action icon="＋" label={t.add} onClick={onAnalysis} /><Action icon="⌕" label={shopLabels[language] || shopLabels.en} onClick={() => onNavigate('shop')} /><Action icon="◔" label={t.ready} onClick={() => onNavigate('intelligence')} /><Action icon="↗" label={t.progress} onClick={() => onNavigate('progress')} /></section><section className="hero-card"><p className="hero-tag">{l.heroTag}</p><p>{l.heroText}</p><button className="outline-btn" onClick={() => onNavigate('intelligence')}>{l.heroButton}</button></section><section className="cards-grid"><article className="card"><h3>{t.suggestion}</h3><p>{t.suggestionText}</p></article><article className="card"><h3>{l.buyerMatch}</h3><ul>{markets.slice(0,3).map((m) => <li key={m.key}><b>{m.label}</b><span>{m.score}%</span></li>)}</ul></article></section></div> }
function Action({ icon, label, onClick }: any) { return <button className="action-card" onClick={onClick}><span className="action-icon">{icon}</span><b>{label}</b><span className="action-arrow">→</span></button> }
function Shop({ price, setPrice, rating, setRating, category, setCategory, onContact }: any) {
  const shopProducts = products.filter((product) => Number(product.price.replace(/[₹,]/g, '')) <= price && (category === 'all' || product.category === category) && product.rating >= rating)
  return <div className="page-stack"><PageTitle eyebrow="SHOP FOR HANDMADE" title="Find crafts you’ll love" action={<span className="soft-badge">{shopProducts.length} results</span>} /><section className="shop-layout"><aside className="filter-panel"><div className="section-heading"><h3>Filters</h3><button className="text-btn" onClick={() => { setPrice(3000); setRating(0); setCategory('all') }}>Clear all</button></div><label className="filter-label">Product category<select value={category} onChange={(e) => setCategory(e.target.value)}><option value="all">All crafts</option><option value="diya">Diyas</option><option value="bamboo">Bamboo</option><option value="textile">Textiles</option></select></label><label className="filter-label">Price range <strong>Up to ₹{price.toLocaleString('en-IN')}</strong><input type="range" min="300" max="3000" step="50" value={price} onChange={(e) => setPrice(Number(e.target.value))} /></label><div className="filter-label"><span>Minimum rating</span><div className="rating-filter">{[1,2,3,4,5].map((star) => <button key={star} className={rating >= star ? 'star active' : 'star'} onClick={() => setRating(star)} aria-label={`${star} stars`}>★</button>)}</div><small>{rating ? `${rating}+ stars` : 'Any rating'}</small></div></aside><section className="shop-results"><div className="result-bar"><span>Showing products within your budget</span><button className="filter-btn">Sort: Recommended</button></div><div className="product-grid">{shopProducts.map((product, index) => <article className="shop-card" key={product.name}><img src={product.image} alt={product.name} /><div className="shop-card-copy"><span className="rating">★★★★★ <small>{(4.6 - index * .2).toFixed(1)}</small></span><h3>{product.name}</h3><p>{product.type}</p><strong>{product.price}</strong><button className="primary-btn full" onClick={onContact}>View product</button></div></article>)}</div>{shopProducts.length === 0 && <div className="empty-state"><h3>No crafts found in this range</h3><p>Try increasing your budget or clearing the rating filter.</p></div>}</section></section></div>
}
function Products({ t, onAdd, onNavigate }: any) { return <div className="page-stack"><PageTitle eyebrow="MY PRODUCTS" title={t.products} action={<button className="primary-btn" onClick={onAdd}>＋ {t.add}</button>} /><section className="grid">{products.map((product) => <article key={product.name} className="product-card"><img src={product.image} alt={product.name} /><div><h3>{product.name}</h3><p>{product.type}</p></div><strong>{product.price}</strong></article>)}</section></div> }
function PageTitle({ eyebrow, title, action }: any) { return <div className="page-title"><div><p className="eyebrow">{eyebrow}</p><h1>{title}</h1></div>{action}</div> }
function Intelligence({ score, onNavigate, roadmap, setRoadmap }: any) { const gaps = [['Digital Catalog','Needs improvement','Buyers need to see your full range in one place.'],['Product Photography','Good','Clean background and consistent lighting can improve trust.'],['Packaging & Labels','Needs work','Add tags, material details, and care instructions.']]; return <div className="page-stack"><PageTitle eyebrow="MARKET READINESS" title="Online Marketplace" action={<span className="score-pill">{score.score}%</span>} /><section className="card"><h3>Readiness breakdown</h3><ProgressBar value={score.score} tone="terracotta" /><p>{score.reason}</p></section><section className="list-card"><h3>Roadmap (Next 30 days)</h3><ul>{['Create product catalog (8 SKUs)','Improve product photography','Finalize packaging labels','List on two marketplaces'].map((step, i) => <li key={step}><label><input type="checkbox" checked={roadmap[i]} onChange={() => setRoadmap((prev: boolean[]) => prev.map((flag, idx) => idx === i ? !flag : flag))} />{step}</label></li>)}</ul></section><section className="list-card"><h3>Gaps to close</h3>{gaps.map(([name, status, text]) => <article key={name} className="gap-item"><header><b>{name}</b><span>{status}</span></header><p>{text}</p></article>)}</section><button className="primary-btn" onClick={() => onNavigate('buyers')}>Find matching buyers</button></div> }
function Buyers({ onContact }: any) { return <div className="page-stack"><PageTitle eyebrow="BUYER DISCOVERY" title="Find your next buyer" action={<button className="filter-btn">⌕ Nearby</button>} /><section className="buyer-grid">{[{name:'Dastkar Emporium', type:'Retail · Delhi', fit:91, asks:'Wants eco-friendly home decor, MOQ 40 units'}, {name:'Crafts of India', type:'Online · Pan India', fit:87, asks:'Needs high quality photos and GST invoice'}, {name:'Weave Bazaar', type:'Boutique · Bengaluru', fit:79, asks:'Interested in handloom pieces and festive bundles'}].map((buyer) => <article key={buyer.name} className="buyer-card"><header><h3>{buyer.name}</h3><span>{buyer.fit}% match</span></header><p className="buyer-type">{buyer.type}</p><p>{buyer.asks}</p><button className="outline-btn" onClick={onContact}>Contact buyer</button></article>)}</section></div> }
function ProgressView({ t }: any) { return <div className="page-stack"><PageTitle eyebrow={t.progress} title={t.progress} action={<span className="month-pill">August 2026</span>} /><section className="card"><h3>Readiness score trend</h3><div className="trend-line"><span style={{ left: '8%' }}>42</span><span style={{ left: '35%' }}>58</span><span style={{ left: '62%' }}>67</span><span style={{ left: '88%' }}>78</span></div><p>Great momentum. Keep improving catalog and packaging for wholesale access.</p></section><section className="stats-grid"><article><b>Products listed</b><strong>12</strong></article><article><b>Buyer replies</b><strong>7</strong></article><article><b>Orders completed</b><strong>5</strong></article><article><b>Repeat buyers</b><strong>2</strong></article></section></div> }
function Help({ onVoice }: any) { return <div className="page-stack"><PageTitle eyebrow="HELP & VOICE" title="हम आपकी मदद के लिए हैं" /><section className="help-card"><h3>Ask in your own language</h3><p>Use voice and ask questions about pricing, markets, packaging, and shipping.</p><VoiceButton onSpeak={onVoice} label="Ask with voice" /></section><section className="faq-list">{[['How to price my product?','Start with material + labor + transport + 20% margin.'],['Which market should I target first?','Online Marketplace is best for your current readiness.'],['How to improve product photos?','Use natural light, plain background, and 3-4 angles.']].map(([q,a]) => <article key={q}><h4>{q}</h4><p>{a}</p></article>)}</section></div> }
function AnalysisModal({ step, onClose }: any) { const steps = ['Product', 'Artisan profile', 'Production capacity', 'Location', 'Digital readiness', 'Finding suitable markets']; return <div className="modal-backdrop"><div className="modal"><button className="modal-close" onClick={onClose}>×</button><h3>Analyzing your profile</h3><p>{steps[step]}</p><ProgressBar value={(step / 5) * 100} tone="green" />{step >= 5 ? <button className="primary-btn" onClick={onClose}>View insights</button> : <small>Please wait…</small>}</div></div> }
function BuyerModal({ onClose, onDone }: any) { return <div className="modal-backdrop"><div className="small-modal"><button className="modal-close" onClick={onClose}>×</button><div className="buyer-head"><h3>Contact buyer</h3><p>Dastkar Emporium</p></div><label>Message<textarea defaultValue="Hello, I would like to share my craft catalog and discuss requirements." /></label><button className="primary-btn" onClick={onDone}>Send message</button></div></div> }
function ProfileModal({ onClose, onSave }: any) { return <div className="modal-backdrop"><div className="small-modal"><button className="modal-close" onClick={onClose}>×</button><h3>Profile</h3><label>Name<input defaultValue="Ramesh Kumar" /></label><label>Craft<input defaultValue="Bamboo craft" /></label><label>Location<input defaultValue="Assam" /></label><label>Monthly capacity<input defaultValue="120 items" /></label><button className="primary-btn" onClick={onSave}>Save profile</button></div></div> }
